language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - libeigen3-dev
  homebrew:
    packages:
      - boost
      - eigen
    update: true
script:
  - cmake .
  - cmake --build .
  - ctest --output-on-failure
